"""ZoeDepth cache utilities for loading pre-computed depth maps.

Handles loading, normalization, and caching of monocular depth
predictions generated by ZoeDepth.
"""

from __future__ import annotations

import os
from typing import Dict, Optional, Tuple

import numpy as np
from absl import logging


class DepthCache:
    """Cache for pre-computed ZoeDepth predictions.

    Args:
        cache_dir: Directory containing .npy depth files.
        normalize: Whether to normalize depth to [0, 1].
        depth_stats: Optional (min, max) for normalization.
    """

    def __init__(
        self,
        cache_dir: str,
        normalize: bool = True,
        depth_stats: Optional[Tuple[float, float]] = None,
    ):
        self.cache_dir = cache_dir
        self.normalize = normalize
        self.depth_stats = depth_stats
        self._cache: Dict[str, np.ndarray] = {}
        self._global_min: Optional[float] = None
        self._global_max: Optional[float] = None

        if depth_stats is not None:
            self._global_min, self._global_max = depth_stats

    def load(self, image_id: str) -> np.ndarray:
        """Load a depth map from cache.

        Args:
            image_id: Image identifier (filename without extension).

        Returns:
            Depth map as float32 array of shape (H, W).
        """
        if image_id in self._cache:
            return self._cache[image_id]

        # Try different path patterns
        candidates = [
            os.path.join(self.cache_dir, f"{image_id}.npy"),
            os.path.join(self.cache_dir, f"{image_id}_depth.npy"),
        ]

        depth = None
        for path in candidates:
            if os.path.exists(path):
                depth = np.load(path).astype(np.float32)
                break

        if depth is None:
            logging.warning(
                f"Depth map not found for {image_id}, returning zeros"
            )
            return np.zeros((256, 256), dtype=np.float32)

        if self.normalize:
            depth = self._normalize_depth(depth)

        return depth

    def _normalize_depth(self, depth: np.ndarray) -> np.ndarray:
        """Normalize depth to [0, 1] range.

        Args:
            depth: Raw depth values.

        Returns:
            Normalized depth in [0, 1].
        """
        if self._global_min is not None and self._global_max is not None:
            d_min, d_max = self._global_min, self._global_max
        else:
            d_min = np.min(depth)
            d_max = np.max(depth)

        if d_max - d_min < 1e-8:
            return np.zeros_like(depth)

        return (depth - d_min) / (d_max - d_min)

    def compute_dataset_stats(
        self, image_ids: list[str]
    ) -> Tuple[float, float]:
        """Compute global min/max depth across a dataset.

        Args:
            image_ids: List of image identifiers.

        Returns:
            Tuple of (global_min, global_max).
        """
        global_min = float("inf")
        global_max = float("-inf")

        for img_id in image_ids:
            path = os.path.join(self.cache_dir, f"{img_id}.npy")
            if not os.path.exists(path):
                continue
            depth = np.load(path)
            global_min = min(global_min, float(np.min(depth)))
            global_max = max(global_max, float(np.max(depth)))

        self._global_min = global_min
        self._global_max = global_max

        logging.info(
            f"Depth stats: min={global_min:.4f}, max={global_max:.4f}"
        )
        return global_min, global_max


# Dataset-specific depth normalization stats
DEPTH_STATS = {
    "cityscapes": (0.0, 80.0),      # meters, typical urban driving range
    "coco_stuff27": (0.0, 10.0),     # meters, typical indoor/outdoor mix
    "nyu_depth_v2": (0.0, 10.0),     # meters, indoor scenes
}


def get_depth_cache(
    dataset_name: str,
    cache_dir: str,
    normalize: bool = True,
) -> DepthCache:
    """Create a DepthCache with dataset-specific normalization.

    Args:
        dataset_name: Dataset name for stat lookup.
        cache_dir: Directory containing depth .npy files.
        normalize: Whether to normalize.

    Returns:
        DepthCache instance.
    """
    stats = DEPTH_STATS.get(dataset_name)
    return DepthCache(
        cache_dir=cache_dir,
        normalize=normalize,
        depth_stats=stats,
    )
